name: Azure Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: List Build Artifacts
        run: ls -R dist

  deploy_job:
      if: github.event_name == 'push'
      needs: build_job
      runs-on: ubuntu-latest
      name: Deploy Job
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Deploy to Azure Web Apps
          uses: Azure/static-web-apps-deploy@v1
          with:
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_06EE9019ACD94517A4AAC5CE6F777ED9 }}
            action: "upload"
            app_location: "dist/helloworld-cicd-github-actions-web-apps/"
